name: Terraform_Manual

on: workflow_dispatch  # To enable a workflow to be triggered manually, 
                       # you need to configure the "workflow_dispatch" event.
jobs: 
  Terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    # env:
    #    aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
    #    aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    defaults:
      run:
        working-directory: terraform
    

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.1.7" 
          terraform_wrapper: false

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4 
        with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ${{ secrets.AWS_REGION }}
           
      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Plan
        id: plan
        run:  terraform plan -var="docker_hub_username=${{ secrets.DOCKER_HUB_USERNAME }}" -var="docker_hub_password=${{ secrets.DOCKER_HUB_PASSWORD }}"

      # - name: Terraform Apply
      #   run: terraform apply -var="docker_hub_username=${{ secrets.DOCKER_HUB_USERNAME }}" -var="docker_hub_password=${{ secrets.DOCKER_HUB_PASSWORD }}" -auto-approve
       
      - name: Terraform destroy
        run: terraform destroy -var="docker_hub_username=${{ secrets.DOCKER_HUB_USERNAME }}" -var="docker_hub_password=${{ secrets.DOCKER_HUB_PASSWORD }}" -auto-approve   
            
